# This is a basic workflow to help you get started with Actions
# This workflow runs the tests on all other branches, except main and deployment
name: Merge upstream branches
on:
  push:
    branches: [ main ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ‘AgdaHTH’
          git config --global user.email 'hilla.halla-aho@helsinki.fi’
          # “git checkout main” is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/IELuomus/extractiontool.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          # etc
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. (edited) 
