# This workflow runs tests on main and on successful testing deploys the changes to deployment branch
name: Django CI
on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
jobs:
   run_main:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
